spring:
  application:
    name: yeoun

  datasource:
    url: jdbc:postgresql://localhost:5432/yeoun
    username: yeoun_user
    password: donghwan02
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    show-sql: true
    open-in-view: false

custom:
  jwt:
    secret-key: "dAboIKLPJAZEPW9o0Xuu56UyMyCHDnZU8cXRD3emlSg="
    access-exp-min: 60
    refresh-exp-day: 30